### ISSUE TITLE
status/statusText is not reflected

### ISSUE THREAD

**Issue by jimmywarting** [Zibri/cloudflare-cors-anywhere#1]
```js
var proxy = 'https://test.cors.workers.dev/?'
var endpoint = 'https://httpbin.org/status/418'
var url = proxy + encodeURIComponent(endpoint)

fetch(url).then(res => {
  console.assert(res.status === 418, 'expected status code to be 418')
  console.assert(res.statusText === `I'M A TEAPOT`, 'expected statusText to be "I\'M A TEAPOT"')
})
```

**Comment by Zibri** [comment]
Sorry.. my bad.. corrected.

**Comment by Zibri** [comment]
hmm.. solution?

**Comment by jimmywarting** [comment]
status code is now ok. looking at the source it looks like statusText should work too, but doesn't

https://github.com/Zibri/cloudflare-cors-anywhere/blob/3859a760b0592dda42b8e9d87bf3721887d5b4de/index.js#L49-L54

😕

**Comment by Zibri** [comment]
It does.. I just answer with the same answer I get:


since that url returns 418 also the fetch returns 418.

**Comment by jimmywarting** [comment]
418 is okey
but i was talking about the statusText

https://jsfiddle.net/o0xmen63/1/
