### ISSUE TITLE
Replace full url script

### ISSUE THREAD

**Issue by churongcon** [Zibri/cloudflare-cors-anywhere#10]
Hello.
I have fetch url like this https://demo.thuan.workers.dev/?http://www.zibri.org/2019/07/your-own-cors-anywhere-proxy-on.html

If site have script like this
<script src="/u/1587166/rotate3.js"></script>
 
How to replace with http://www.zibri.org//u/1587166/rotate3.js

**Comment by Zibri** [comment]
This is not intended as a prosy.
Is intended to retrieve data.
It is your code that must change all local references to absolute references pointing to your own cors proxy.
