### ISSUE TITLE
How to prevent abuse of my CORS proxy?

### ISSUE THREAD

**Issue by kilgarenone** [Zibri/cloudflare-cors-anywhere#12]
Since Cloudflare Workers is priced by hits, how do I prevent people from calling and abusing it for themselves?

**Comment by frossigneux** [comment]
I can see two things to prevent:
- An unique IP abusing the service for fetching resources from many websites
- A website (unique Referer) using the CORS proxy for fetching resources
Maybe that we could implement a ban system using cache or KV, and allowing a quota/day?

**Comment by rahulkumarsingh73690** [comment]
@kilgarenone How do you prevent abuse of cors? Randomly my cors is abused a lot
