### ISSUE TITLE
You don't expose any response headers

### ISSUE THREAD

**Issue by jimmywarting** [Zibri/cloudflare-cors-anywhere#2]
```js
var proxy = 'https://test.cors.workers.dev/?'
var endpoint = 'https://httpbin.org/base64/SFRUUEJJTiBpcyBhd2Vzb21l'
var url = proxy + encodeURIComponent(endpoint)

fetch(url).then(res => {
  console.assert(res.headers.get('content-length') === '18', 'Expected content-length to be 18')
})
```

**Comment by Zibri** [comment]
Hmm because this is like cors anywhere and works as transparently as possible. If you have any code suggestion I will listen...

**Comment by Zibri** [comment]
now corrected and exposes the status and statusText..

**Comment by jimmywarting** [comment]
> now corrected and exposes the status and statusText..

Unrelated to this issue but good work!

>  If you have any code suggestion I will listen...

when you get the response object back from making the request you do call `fix(myHeaders)`...

https://github.com/Zibri/cloudflare-cors-anywhere/blob/3859a760b0592dda42b8e9d87bf3721887d5b4de/index.js#L43-L46

You could get all those response header keys there and set them in a new response header
`Access-Control-Expose-Headers: <header-name>, <header-name>, ...`

```js
var myHeaders = new Headers({'x-foo': 'bar'})

var exposeHeaders = [...new Headers(myHeaders).keys()]
myHeaders.set("Access-Control-Expose-Headers", exposeHeaders.join(', '))
```

**Comment by Zibri** [comment]
Hmm.. yes but why? 
All headers I get from the fetch I send back in the response.
They are all there.
Am I missing something?

**Comment by jimmywarting** [comment]
yes, all headers get sent back 👍 
..but you are not able to read any of them with javascript 

except for 

- Cache-Control
- Content-Language
- Content-Type
- Expires
- Last-Modified
- Pragma

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

So you can not get something and figure out what how big the response is and do things accordingly.
cuz you are not allowed to read other response header when dealing with cors. that's why `Access-Control-Expose-Headers` exist

`res.headers.get('content-length')` returns `null` if you don't expose it

**Comment by Zibri** [comment]
Hmmmm... you gave me an idea...
I could return Access-Control-Expose-Headers followed by all headers
name returned by the fetch (sinche the * wildacrd is not yet fully
supported)

On Wed, 2019-07-17 at 13:44 -0700, Jimmy Wärting wrote:
Access-Control-Expose-Headers

**Comment by Zibri** [comment]
check it out now and let me know...

**Comment by jimmywarting** [comment]
Looks like it almost works.
still didn't get the `content-length` from my example above 😕 

```js
var proxy = 'https://test.cors.workers.dev/?'
var endpoint = 'https://httpbin.org/base64/SFRUUEJJTiBpcyBhd2Vzb21l'
var url = proxy + encodeURIComponent(endpoint)

fetch(url).then(res => {
  console.assert(res.headers.get('content-length') === '18', 'Expected content-length to be 18')
})
```
all i got was:

access-control-allow-credentials,access-control-allow-origin,cf-ray,connection,content-type,date,expect-ct,referrer-policy,server,transfer-encoding,x-content-type-options,x-frame-options,x-xss-protection

doe i was able to read x-xss-protection

**Comment by Zibri** [comment]
Now it exposes all headers and also exposes all received headers in "cors-received-headers".

**Comment by Zibri** [comment]
Here we go:
```js
fetch('https://test.cors.workers.dev/?https://httpbin.org/post', {
  method: 'post',
  headers: { 'x-foo': 'bar', 'x-bar': 'foo', 'x-cors-headers': JSON.stringify({"additional_header": "value"}) }
}).then(r => {console.log(JSON.parse(r.headers.get("cors-received-headers")));return r.json()}).then(console.log)
```
