### ISSUE TITLE
ReferenceError: cookies is not defined

### ISSUE THREAD

**Issue by dlackty** [Zibri/cloudflare-cors-anywhere#20]
Hi @Zibri 
Thanks for this nice little project! However, when I want to try this, I found that the latest commit af9eb6b causes an error:

```ReferenceError: cookies is not defined```

Could you please have a look? Thank you!

**Comment by 07h** [comment]
I have the same problem. how do I solve it?

**Comment by Zibri** [comment]
My bad.. I merged a pull request without checking it..
It should be fixed now.

**Comment by dlackty** [comment]
Fixed in 135b69ce6e3b918730d0d73717f38ae6b2ad6477. Thanks @Zibri
