### ISSUE TITLE
Doesn't allow forbidden headers

### ISSUE THREAD

**Issue by jimmywarting** [Zibri/cloudflare-cors-anywhere#3]
Some request requires cookies, and other api's looks at origin and only allows themself to make request.

but browsers [forbid some headers](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name) for being sent

example:

```js
var proxy = 'https://test.cors.workers.dev/?'
var endpoint = 'https://httpbin.org/get'
var url = proxy + encodeURIComponent(endpoint)
var headers = { 'cookie': 'foo=bar;' }

fetch(url, { headers })
  .then(res => res.json())
  .then(console.log)
```

so there are no alternative way to set forbidden request headers. suggestion:

```js
var headers = [['cookie', 'foo=bar']]

new URLSearchParams([
  ['url', 'https://httpbin.org/get'],
  ['headers', JSON.stringify(headers)]
]) 
// "url=https%3A%2F%2Fhttpbin.org%2Fget&headers=%5B%5B%22cookie%22%2C%22foo%3Dbar%22%5D%5D"
```

**Comment by Zibri** [comment]
right.. fork and make a pull request

**Comment by Zibri** [comment]
Unless I could implement a header...
If colled for example with Header zibcookie it can pass it as cookie.... or something like that.
What do you think?

**Comment by Zibri** [comment]
or even bettr I could implement a custom header "customhdeader: { }" with an object definind the headers to be passed.

**Comment by jimmywarting** [comment]
Both ideas could work.

> If colled for example with Header zibcookie it can pass it as cookie.... or something like that.

To make it a little bit more generic I would maybe go for something like a `x-cors-` thats get stripped away when the proxy makes the request.

```js
var proxy = 'https://test.cors.workers.dev/?'
var endpoint = 'https://httpbin.org/get'
var url = proxy + encodeURIComponent(endpoint)
var headers = [
  'x-cors-cookie': 'foo=bar',
  'x-cors-origin': 'https://example.com'
]

fetch(url, { headers })
  .then(res => res.json())
  .then(console.log)
```

**Comment by Zibri** [comment]
isn't it better:
'x-cors-headers' , <json object>
?

**Comment by jimmywarting** [comment]
sure, if the server allows it

https://stackoverflow.com/questions/686217/maximum-on-http-header-values

**Comment by Zibri** [comment]
now it does!!!

```
fetch('https://test.cors.workers.dev/?https://httpbin.org/post', {
  method: 'post',
  headers: { 'x-foo': 'bar', 'x-bar': 'foo', 'x-cors-headers': JSON.stringify({"newheader": "newvalue"}) }
}).then(r => r.json()).then(console.log)

```
