### ISSUE TITLE
Black list

### ISSUE THREAD

**Issue by CrazyShaman1989** [Zibri/cloudflare-cors-anywhere#4]
Hello my dear friend!

How to ban all sites without making a list, except those that are whitelist?

**Comment by Zibri** [comment]
blacklist = [ ".*" ]

whitelist = all who you authorize

if you read the code is straightforward.

**Comment by Zibri** [comment]
in the code the relevant line is:
```
if ((!isListed(fetch_url, blacklist)) && (isListed(orig, whitelist)))
```

so, if you want to use whitelist only:

blacklist = [ ];  // no blacklist
whitelist = [ "first", "second" ];

in this way only whitelist will be considered.

**Comment by CrazyShaman1989** [comment]
Tried on the example of your site

blacklist = [ ".*" ];           // regexp for blacklisted urls
whitelist = [ "^http.?://www.zibri.org$", "zibri.org$", "test\\..*" ]; 

[https://prnt.sc/ol42nt](Screenshot)

**Comment by Zibri** [comment]
try this:
```
blacklist = [  ]; // regexp for blacklisted urls
whitelist = [ "^http.?://www.zibri.org$", "zibri.org$", "test\.." ];
```

**Comment by Zibri** [comment]
But if you need to whitelist ORIGINS then you must change the code to:
```
if ((!isListed(fetch_url, blacklist)) && (isListed(fetch_url, whitelist)))
```
