### ISSUE TITLE
Redirection is not working

### ISSUE THREAD

**Issue by sajjadalis** [Zibri/cloudflare-cors-anywhere#8]
I just tried this on cloudflare and it's getting 403 Moved Permanently error with null response for access-control-allow-origin.

Its because the URL i tried redirects to another URL and that is the one send the actual header response. If i use that redirected URL then this cors proxy is working fine.

While cors anywhere (https://cors-anywhere.herokuapp.com/) works fine for same URL, which redirects to next and then get the response i need.

Any way to get redirection fixed for this proxy? I need to host my own solution and this one seems pretty easier to setup.

Thank for this solution.

**Comment by Zibri** [comment]
I will look into it but if anyone wants to do a PULL request he is more than welcome.
